name: mindintrest_user
description: Mind Interest User App
version: 1.0.0+6
publish_to: none


environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animated_shimmer: ^1.0.0
  another_flushbar: ^1.10.29
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.13
  dartz: ^0.10.1
  dio: ^5.3.2
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  file_picker: ^5.2.10
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  flutter_local_notifications: ^15.1.0+1
  firebase_messaging: ^13.1.0
  firebase_storage: ^10.2.9
  flutter_inappwebview: ^5.7.2+2
  url_launcher: ^6.1.6

  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.5.1
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  flutter_secure_storage:
  freezed_annotation:
  gap: ^2.0.0
  go_router: ^10.0.0
  google_fonts: ^4.0.4
  hooks_riverpod: ^2.3.8
  intl: ^0.17.0
#  jitsi_meet_wrapper: ^0.0.4
#  twilio_programmable_video: ^1.1.1
  wakelock: ^0.6.2
  after_layout:
  native_device_orientation:
  permission_handler: any
  # jitsi_meet: ^4.0.0
  logger: ^2.0.1
  paginate_firestore: ^1.0.3
  pinput: ^2.2.21
  readmore: ^2.1.0
  timeago: ^3.2.2
  sliding_up_panel: ^2.0.0+1
  webview_flutter: ^4.2.2
  firebase_analytics: ^9.1.10
  smooth_star_rating_nsafe: ^1.0.0+1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: 
  mocktail:
  very_good_analysis: ^3.1.0
  chewie_audio: ^1.5.0


dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  intl: ^0.18.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - .env.prod
    - .env.dev


