// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCniJ2cNU9KCC2F5nSyIRiFiFAnXjhmFho',
    appId: '1:568900220648:android:e9ce31c1bb5202ab293b5d',
    messagingSenderId: '568900220648',
    projectId: 'mind-interest',
    storageBucket: 'mind-interest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ZHYFUf1EPrhU1dxwyN6h5UPvFj6PXSs',
    appId: '1:568900220648:ios:f558f48821c67006293b5d',
    messagingSenderId: '568900220648',
    projectId: 'mind-interest',
    storageBucket: 'mind-interest.appspot.com',
    iosClientId: '568900220648-6tqud2r3ft0cp6qvv6b01t0nvh43gg1b.apps.googleusercontent.com',
    iosBundleId: 'com.mindinterest.mindinterest-user.dev',
  );
}
